topology:
  host_interfaces:
   - 0
   - 1
   - 2
   - 3
   - 4
   - 5
   - 6
   - 7
   - 8
   - 9
   - 10
   - 11
   - 12
   - 13
   - 14
   - 15
   - 16
   - 17
   - 18
   - 19
   - 20
   - 21
   - 22
   - 23
   - 24
   - 25
   - 26
   - 27
   - 28
   - 29
   - 30
   - 31
   - 32
   - 33
   - 34
   - 35
   - 36
   - 37
   - 38
   - 39
   - 40
   - 41
   - 44
   - 45
   - 46
   - 49
   - 50
   - 51
   - 54
   - 55
   - 56
   - 59
   - 60
   - 61
   - 62
   - 63
   - 64
   - 65
   - 66
   - 67
   - 68
   - 69
   - 70
   - 71
   - 72
   - 73
   - 74
   - 75
   - 76
   - 78
   - 79
   - 80
   - 82
   - 84
   - 85
   - 86
   - 87
   - 89
   - 90
   - 92
   - 93
   - 94
   - 96
   - 97
   - 99
   - 100
   - 101
   - 103
  disabled_host_interfaces:
   - 77
   - 81
   - 83
   - 88
   - 91
   - 95
   - 98
   - 102
  VMs:
    ARISTA01T1:
      vlans:
        - 42
        - 43
      vm_offset: 0
    ARISTA02T1:
      vlans:
        - 47
        - 48
      vm_offset: 1
    ARISTA03T1:
      vlans:
        - 52
        - 53
      vm_offset: 2
    ARISTA04T1:
      vlans:
        - 57
        - 58
      vm_offset: 3

configuration_properties:
  common:
    dut_asn: 4200065100
    dut_type: ToRRouter
    swrole: leaf
    podset_number: 200
    tor_number: 16
    tor_subnet_number: 2
    max_tor_subnet_number: 16
    tor_subnet_size: 128
    spine_asn: 65534
    leaf_asn_start: 4200064600
    tor_asn_start: 4200065100
    failure_rate: 0
    nhipv4: 10.10.246.100
    nhipv6: FC0A::C9

configuration:
  ARISTA01T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.32
        - FC00::21
    interfaces:
      Loopback0:
        ipv4: 100.1.0.33/32
        ipv6: 2064:100::33/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.33/31
        ipv6: fc00::22/126
    bp_interface:
      ipv4: 10.10.246.33/24
      ipv6: fc0a::23/64

  ARISTA02T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.34
        - FC00::25
    interfaces:
      Loopback0:
        ipv4: 100.1.0.35/32
        ipv6: 2064:100::26/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.35/31
        ipv6: fc00::26/126
    bp_interface:
      ipv4: 10.10.246.35/24
      ipv6: fc0a::26/64

  ARISTA03T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.36
        - FC00::29
    interfaces:
      Loopback0:
        ipv4: 100.1.0.37/32
        ipv6: 2064:100::2A/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.37/31
        ipv6: fc00::2A/126
    bp_interface:
      ipv4: 10.10.246.37/24
      ipv6: fc0a::2A/64

  ARISTA04T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.38
        - FC00::2D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.39/32
        ipv6: 2064:100::2E/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.39/31
        ipv6: fc00::2E/126
    bp_interface:
      ipv4: 10.10.246.39/24
      ipv6: fc0a::2E/64

