ansible_user: "{{ secret_group_vars['fanout']['ansible_ssh_user'] }}"
ansible_password: "{{ secret_group_vars['fanout']['ansible_ssh_pass'] }}"
fanout_mlnx_user: admin
fanout_mlnx_password: admin
fanout_sonic_user: admin
fanout_sonic_password: password

# Credential for accessing the network cli interface
fanout_network_user: netadmin
fanout_network_password: netpassword

# Credential for accessing the Linux shell
fanout_shell_user: shelladmin
fanout_shell_password: shellpassword
