---
ansible_user: "{{ secret_group_vars['vm_host']['ansible_user'] }}"
ansible_password: "{{ secret_group_vars['vm_host']['ansible_password'] }}"
ansible_sudo_pass: "{{ secret_group_vars['vm_host']['ansible_sudo_pass'] }}"
